# .golangci.yml
# Version 2 configuration for golangci-lint.

version: "2"

run:
  timeout: 5m
  tests: false

linters:
  default: none
  enable:
    - errcheck
    - govet
    - staticcheck
    - ineffassign
    - misspell
    - bodyclose
    - durationcheck
    - errorlint
    - nolintlint
    - rowserrcheck
    - sqlclosecheck
    - wastedassign
    - whitespace

  settings:
    govet:
      enable-all: true
      disable:
        - fieldalignment
    errorlint:
      errorf: true

formatters:
  enable:
    - gofmt
    - goimports
